source "https://rubygems.org"

gem "rails", "4.1.0.rc1"
# Use SCSS for stylesheets
gem "sass-rails", "~> 4.0.1"
# Use Uglifier as compressor for JavaScript assets
gem "uglifier", ">= 1.3.0"
# Use CoffeeScript for .js.coffee assets and views
gem "coffee-rails", "~> 4.0.0"
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem "therubyracer",  platforms: :ruby
gem "jquery-ui-rails", "~> 4.2.0"

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem "turbolinks"

gem "pg", "~> 0.17"
gem "foreigner", "~> 1.6.1"
# resolves DEPRECATION warnings present in 0.9.0
gem "money-rails", github: "RubyMoney/money-rails", ref: "c0bf5ef27b55938933c189a5324a810028ff3303"
gem "carrierwave", "~> 0.10.0"
gem "mini_magick", "~> 3.7.0"

# # Rails 4.1 (temporary)
gem "jquery-rails", "~> 3.0.4"
gem "simple_form"
gem "kaminari"
gem "cells", "~> 3.10.0"

# Deployment
gem "mina", github: "nadarei/mina"
gem "dotenv-rails", "~> 0.9.0"
gem "whenever",     "~> 0.8.2", require: false
gem "foreman",      "~> 0.63"
gem "newrelic_rpm", "~> 3.6.7.152"
gem "puma",         "~> 2.6.0"

# backup
gem "backup",  "~> 3.1.3"
gem "excon",   "~> 0.17.0"  # backup 3.1.3 requires excon ~> 0.17.0
gem "fog",     "~> 1.9.0"   # backup 3.1.3 requires fog ~> 1.9.0
gem "net-ssh", "2.5.2"      # backup 3.1.3 requires net-ssh 2.5.2


gem "devise"
gem "devise_invitable"
gem "foundation-rails"

gem "compass-rails"
gem "font-awesome-rails"

group :development, :test do
  gem "pry"
  gem "pry-debugger"
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
  # gem "guard-bundler"
  gem "guard-rails"
  gem "guard-minitest"
  gem "quiet_assets"
  gem "annotate"
  # gem "rails_layout"
  # gem "rb-fchange", :require=>false
  # gem "rb-fsevent", :require=>false
  # gem "rb-inotify", :require=>false
end

group :test do
  gem "capybara"
  gem "minitest-spec-rails"
  gem "mocha"
  gem "factory_girl_rails"
  gem "database_cleaner", "~> 1.2"
  gem "simplecov", "~> 0.8.2"
end
